import React from 'react';
import { motion } from 'motion/react';
import { Users, Heart, Share2, MessageSquare, Zap } from 'lucide-react';

const showcaseItems = [
  {
    title: "V12 Manifold",
    author: "HyperEngine",
    likes: "2.4k",
    comments: 124,
    image: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&q=80&w=600",
    size: "large"
  },
  {
    title: "Aero Frame",
    author: "SkyBuild",
    likes: "1.2k",
    comments: 45,
    image: "https://images.unsplash.com/photo-1544383120-d4347715fbc3?auto=format&fit=crop&q=80&w=400",
    size: "small"
  },
  {
    title: "Fusion Core",
    author: "ThermoSpec",
    likes: "3.1k",
    comments: 89,
    image: "https://images.unsplash.com/photo-1531746790731-6c087fecd05a?auto=format&fit=crop&q=80&w=400",
    size: "medium"
  },
  {
    title: "Lathe Post",
    author: "PrecisionX",
    likes: "942",
    comments: 12,
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=400",
    size: "small"
  }
];

const CommunityShowcase: React.FC = () => {
  return (
    <section className="py-24 px-8 bg-transparent relative overflow-hidden">
      <div className="max-w-7xl mx-auto relative z-10">
        <div className="flex flex-col md:flex-row justify-between items-end mb-24 gap-8">
           <div className="space-y-6">
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-500/10 border border-indigo-500/20 rounded-xl">
                <Users size={14} className="text-indigo-400" />
                <span className="text-[10px] font-black uppercase tracking-widest text-indigo-400 font-unique">Global Synthesis Network</span>
              </div>
              <h2 className="text-6xl md:text-9xl font-black tracking-tightest uppercase font-unique leading-none">
                Community <br />
                <span className="text-indigo-500">Showcase</span>
              </h2>
           </div>
           <div className="max-w-sm text-left md:text-right">
              <p className="text-xl text-foreground dark:text-zinc-100 font-technical leading-relaxed tracking-tight font-medium">
                Explore the latest structural innovations generated by a global network of engineers. Real-time peer verification enabled at the kernel level.
              </p>
           </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 md:grid-rows-2 gap-6 h-[800px] md:h-[600px]">
          {showcaseItems.map((item, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 }}
              viewport={{ once: true }}
              className={`
                group relative bg-card border border-border rounded-[2.5rem] overflow-hidden 
                ${item.size === 'large' ? 'md:col-span-2 md:row-span-2' : ''}
                ${item.size === 'medium' ? 'md:col-span-2 md:row-span-1' : ''}
                ${item.size === 'small' ? 'md:col-span-1 md:row-span-1' : ''}
                hover:border-indigo-500/30 transition-all duration-700
              `}
            >
              <img 
                src={item.image} 
                className="absolute inset-0 w-full h-full object-cover opacity-60 group-hover:scale-110 transition-transform duration-[1s] transition-opacity group-hover:opacity-100"
                alt={item.title}
              />
              <div className="absolute inset-0 bg-gradient-to-t from-zinc-900 via-zinc-900/40 to-transparent" />
              
              <div className="absolute bottom-8 left-8 right-8">
                 <div className="flex justify-between items-end">
                    <div>
                      <p className="text-[10px] font-black text-indigo-300 uppercase tracking-widest mb-1 drop-shadow-sm">@{item.author}</p>
                      <h3 className="text-2xl font-black text-white font-unique tracking-tighter uppercase drop-shadow-md">{item.title}</h3>
                    </div>
                    <div className="flex items-center gap-4 text-white font-black text-[10px] drop-shadow-sm">
                       <div className="flex items-center gap-1">
                          <Heart size={12} className="group-hover:text-red-500 transition-colors" />
                          <span>{item.likes}</span>
                       </div>
                    </div>
                 </div>
              </div>

              {item.size === 'large' && (
                <div className="absolute top-8 left-8">
                   <div className="px-4 py-2 bg-indigo-600 rounded-xl flex items-center gap-2 shadow-2xl">
                      <Zap size={12} className="text-white fill-white" />
                      <span className="text-[10px] font-black text-white uppercase tracking-widest">Featured</span>
                   </div>
                </div>
              )}
            </motion.div>
          ))}
        </div>

        <div className="mt-16 flex justify-center">
           <motion.button
             whileHover={{ scale: 1.05 }}
             whileTap={{ scale: 0.95 }}
             className="px-12 py-5 bg-white text-black rounded-2xl font-black text-xs uppercase tracking-[0.2em] shadow-2xl flex items-center gap-4 hover:bg-zinc-200 transition-colors"
           >
              <Share2 size={16} />
              Publish your first synthesis
           </motion.button>
        </div>
      </div>
    </section>
  );
};

export default CommunityShowcase;
